CREATE DATABASE `demo`;
USE `demo`;

-- Size
CREATE TABLE `size` (
  `id` INT PRIMARY KEY,
  `name` VARCHAR(30) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Color
CREATE TABLE `color` (
  `id` INT PRIMARY KEY,
  `name` VARCHAR(30) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Category
CREATE TABLE `category` (
  `id` INT PRIMARY KEY,
  `name` VARCHAR(30) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ClothInfo
CREATE TABLE `cloth` (
  `id` INT PRIMARY KEY,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `unit_price` INT NOT NULL,
  `category_id` INT NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`category_id`) REFERENCES `category`(`id`)
);

-- Inventory
CREATE TABLE `inventory` (
  `id` INT PRIMARY KEY,
  `cloth_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`cloth_id`) REFERENCES `cloth`(`id`),
  FOREIGN KEY (`color_id`) REFERENCES `color`(`id`),
  FOREIGN KEY (`size_id`) REFERENCES `size`(`id`)
);

