apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8080 
      targetPort: 8080
  selector:
    app: api-server