ALLOWED_DOMAIN = 'www.deltaww-energy.com'
ALLOWED_HOST = 'www.deltaww-energy.com'
ALLOWED_MEDIA_TYPE = 'application/json'
ALLOWED_REFERER = 'www.svc.deltaww-energy.com'
HEADER_FROM = 'hello@deltaww-energy.com'
WHITE_LIST='/test_connection'